# Generated by Django 5.1.6 on 2025-02-21 23:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_referral_codes(apps, schema_editor):
    """
    Populate the referral_code field with unique UUIDs for all existing users.
    """
    User = apps.get_model('users', 'User')  # Replace 'users' with your app name
    for user in User.objects.all():
        user.referral_code = uuid.uuid4()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),  # Replace with the previous migration
    ]

    operations = [
        # Add the referral_code field without the unique constraint first
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),  # Allow null temporarily
        ),

        # Populate referral_code for existing users
        migrations.RunPython(populate_referral_codes),

        # Add the unique constraint to the referral_code field
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),

        # Add the credits field
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),

        # Create the Referral model
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_date', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),

        # Create the ReferralBonus model
        migrations.CreateModel(
            name='ReferralBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_date', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonuses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]