# Generated by Django 5.1.6 on 2025-02-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckimage',
            name='image',
            field=models.ImageField(default='service-44.jpg', upload_to='trucks/'),
        ),
    ]
