# Generated by Django 5.1.6 on 2025-02-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_truckimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='tracker_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
