# Generated by Django 5.1.6 on 2025-05-26 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_truck_tracker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.truck'),
        ),
    ]
