# Generated by Django 5.1.6 on 2025-04-16 06:25

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_trackertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackertoken',
            name='username',
        ),
        migrations.AddField(
            model_name='trackertoken',
            name='user',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=models.CASCADE,
                null=True  # Temporary allow null
            ),
        ),
    ]
