# Generated by Django 5.1.6 on 2025-04-16 06:28

from django.db import migrations, models
from django.conf import settings

def populate_users(apps, schema_editor):
    User = apps.get_model('users', 'User')
    TrackerToken = apps.get_model('tracker', 'TrackerToken')
    
    for token in TrackerToken.objects.all():
        try:
            token.user = User.objects.get(username=token.username)
            token.save()
        except User.DoesNotExist:
            token.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20250416_0725'),
    ]

    operations = [
        migrations.RunPython(populate_users),
        migrations.AlterField(
            model_name='trackertoken',
            name='user',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=models.CASCADE,
                null=False  # Now make it required
            ),
        ),
    ]
