# Generated by Django 5.1.6 on 2025-05-17 11:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20250416_0728'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geofencealert',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='trackingevent',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterUniqueTogether(
            name='trackertoken',
            unique_together={('user', 'token')},
        ),
    ]
