# Generated by Django 5.1.6 on 2025-05-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_geofencealert_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='battery_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='gps_satellites',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='is_moving',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracker',
            name='signal_strength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='battery_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='signal_strength',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
