# Generated by Django 5.1.6 on 2025-05-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_tracker_battery_level_tracker_gps_satellites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingevent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
